# Generated by Django 2.2.16 on 2022-09-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='ff24eca8-f752-4b5f-a63f-08c4c48f8e19', max_length=100, null=True, verbose_name='Confirmation code'),
        ),
    ]
