# Generated by Django 2.2.16 on 2022-09-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='460a8861-9a35-4300-8b84-1f6227a5c2b6', max_length=100, null=True, verbose_name='Confirmation code'),
        ),
    ]
