# Generated by Django 2.2.16 on 2022-09-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220914_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='dbf6ba32-ebca-4917-817c-2c888c2b952e', max_length=100, null=True, verbose_name='Confirmation code'),
        ),
    ]
