# Generated by Django 2.2.16 on 2022-09-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220913_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='4e10dfe5-0e46-4535-9613-e689e5e05ec9', max_length=100, null=True, verbose_name='Confirmation code'),
        ),
    ]
