# Generated by Django 2.2.16 on 2022-09-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220913_1043'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_author_review',
        ),
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='82d16eb2-d83c-4d75-9d44-7aea27e8f8bd', max_length=100, null=True, verbose_name='Confirmation code'),
        ),
    ]
