# Generated by Django 2.2.16 on 2022-09-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220913_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='fbb22371-e4aa-4757-8c33-486cae902522', max_length=100, null=True, verbose_name='Confirmation code'),
        ),
    ]
