# Generated by Django 2.2.16 on 2022-09-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20220913_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='4428d370-fbda-4e75-b03f-55a0f9cc9bf4', max_length=100, null=True, verbose_name='Confirmation code'),
        ),
    ]
